### ISSUE TITLE
MobilenetV2 model error!

### ISSUE THREAD

**Issue by zhangxujinsh** [610265158/mobilenetv3_centernet#12]
1:  set  config.MODEL.net_structure='MobilenetV2'
2: python train.py  and  get the following info:
          Failed to create op 0: Op(op=<function convolution2d at 0x7ff585f365f0>, params={'stride': 2, 'num_outputs': 32, 'kernel_size': [3, 3]}, multiplier_func=<function depth_multiplier at 0x7ff56753c170>) params: {'stride': 2, 'num_outputs': 16, 'kernel_size': [3, 3]}
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    trainner.train()
  File "/ws/opensource/face/fd/tensorflow_fd/centernet/mobilenetv3_centernet_mnet025/lib/core/base_trainer/net_work.py", line 525, in train
    self.train_loop()
  File "/ws/opensource/face/fd/tensorflow_fd/centernet/mobilenetv3_centernet_mnet025/lib/core/base_trainer/net_work.py", line 362, in train_loop
    self.build()
  File "/ws/opensource/face/fd/tensorflow_fd/centernet/mobilenetv3_centernet_mnet025/lib/core/base_trainer/net_work.py", line 265, in build
    scope, images_, hm_, wh_,weight_, training)
  File "/ws/opensource/face/fd/tensorflow_fd/centernet/mobilenetv3_centernet_mnet025/lib/core/base_trainer/net_work.py", line 147, in tower_loss
    hm_loss,wh_loss = centernet.forward(images, kps_hm_, wh_,weights_, training)
  File "/ws/opensource/face/fd/tensorflow_fd/centernet/mobilenetv3_centernet_mnet025/lib/core/model/centernet.py", line 51, in forward
    origin_fms=self.backbone(inputs,training_flag)
  File "/ws/opensource/face/fd/tensorflow_fd/centernet/mobilenetv3_centernet_mnet025/lib/core/model/net/mobilenet/backbone.py", line 52, in mobilenet_ssd
    _,endpoint = mobilenet_v2_035(image,is_training=is_training,base_only=True,finegrain_classification_mode=False)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/ws/opensource/face/fd/tensorflow_fd/centernet/mobilenetv3_centernet_mnet025/lib/core/model/net/mobilenet/mobilenet_v2.py", line 157, in mobilenet
    **kwargs)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/ws/opensource/face/fd/tensorflow_fd/centernet/mobilenetv3_centernet_mnet025/lib/core/model/net/mobilenet/mobilenet.py", line 347, in mobilenet
    net, end_points = mobilenet_base(inputs, scope=scope, **mobilenet_args)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/ws/opensource/face/fd/tensorflow_fd/centernet/mobilenetv3_centernet_mnet025/lib/core/model/net/mobilenet/mobilenet.py", line 270, in mobilenet_base
    net = opdef.op(net, **params)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py", line 1159, in convolution2d
    conv_dims=2)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1700, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/layers/base.py", line 548, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 824, in __call__
    self._maybe_build(inputs)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2146, in _maybe_build
    self.build(input_shapes)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 165, in build
    dtype=self.dtype)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/layers/base.py", line 466, in add_weight
    self._handle_weight_regularization(name, variable, regularizer)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1928, in _handle_weight_regularization
    self.add_loss(functools.partial(_loss_for_variable, variable))
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/layers/base.py", line 292, in add_loss
    loss_tensor = regularizer()
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1092, in _tag_unconditional
    loss = loss()
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1921, in _loss_for_variable
    regularization = regularizer(v)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/regularizers.py", line 106, in l2
    name='scale')
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "/ws/data/virtualenvs/py379_gw/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1273, in internal_convert_to_tensor
    (dtype.name, value.dtype.name, value))

ValueError: Tensor conversion requested dtype float32 for Tensor with dtype bool: <tf.Tensor 'training_flag:0' shape=<unknown> dtype=bool>

Could you give me a hint?

**Comment by 610265158** [comment]
Sorry, i am no longer work with tensorflow, so the code is not maintained. Feel really sorry for that.

**Comment by zhangxujinsh** [comment]
Thanks for your reply!   Good luck!
